### ISSUE TITLE
Clean build: Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by frel** [jaredsburrows/android-gradle-java-template#19]
Hi,

 I'm getting the following gradle error:

> Execution failed for task ':test-lib:compileReleaseJavaWithJavac'.
> > javax/tools/DiagnosticListener : Unsupported major.minor version 52.0

I'm using java 7. It's set both in grade and in the project settings for Android Studio.
Do you have any ideas? version 52 is Java 8. Thanks

**Comment by jaredsburrows** [comment]
@frel The `classpath 'net.ltgt.gradle:gradle-errorprone-plugin:0.0.8'` Google ErrorProne plugin is compiling with Java 8.

I can make it work with Java 7. I highly suggest you upgrade to Java 8.

**Comment by jaredsburrows** [comment]
@frel Thanks for letting me know. I have fixed it here: https://travis-ci.org/jaredsburrows/android-gradle-java-template/builds/123095301.

**Comment by frel** [comment]
Thanks!

**Comment by jaredsburrows** [comment]
@frel Since Android 24 is out, you need jdk8 to use it. So make sure you start using jdk8:

```
compileSdkVersion 'android-24' requires JDK 1.8 or later to compile.
```
